title: Drawpile
description: Collaborative Drawing
domain: docs.drawpile.net
baseurl: "/"
url: "https://docs.drawpile.net"
github_username: drawpile
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og/logo.png
